/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAmigosRouteImport } from './routes/_authenticated/amigos'
import { Route as AuthenticatedCanaisIndexRouteImport } from './routes/_authenticated/canais.index'
import { Route as AuthenticatedCanaisChannelIdRouteImport } from './routes/_authenticated/canais.$channelId'
import { Route as AuthenticatedConviteCodeRouteImport } from './routes/_authenticated/convite.$code'
import { Route as AuthenticatedDmUserIdRouteImport } from './routes/_authenticated/dm.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAmigosRoute = AuthenticatedAmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCanaisIndexRoute =
  AuthenticatedCanaisIndexRouteImport.update({
    id: '/canais/',
    path: '/canais/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCanaisChannelIdRoute =
  AuthenticatedCanaisChannelIdRouteImport.update({
    id: '/canais/$channelId',
    path: '/canais/$channelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConviteCodeRoute =
  AuthenticatedConviteCodeRouteImport.update({
    id: '/convite/$code',
    path: '/convite/$code',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDmUserIdRoute = AuthenticatedDmUserIdRouteImport.update({
  id: '/dm/$userId',
  path: '/dm/$userId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/canais/$channelId': typeof AuthenticatedCanaisChannelIdRoute
  '/convite/$code': typeof AuthenticatedConviteCodeRoute
  '/dm/$userId': typeof AuthenticatedDmUserIdRoute
  '/canais/': typeof AuthenticatedCanaisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/canais/$channelId': typeof AuthenticatedCanaisChannelIdRoute
  '/convite/$code': typeof AuthenticatedConviteCodeRoute
  '/dm/$userId': typeof AuthenticatedDmUserIdRoute
  '/canais': typeof AuthenticatedCanaisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/amigos': typeof AuthenticatedAmigosRoute
  '/_authenticated/canais/$channelId': typeof AuthenticatedCanaisChannelIdRoute
  '/_authenticated/convite/$code': typeof AuthenticatedConviteCodeRoute
  '/_authenticated/dm/$userId': typeof AuthenticatedDmUserIdRoute
  '/_authenticated/canais/': typeof AuthenticatedCanaisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/amigos'
    | '/canais/$channelId'
    | '/convite/$code'
    | '/dm/$userId'
    | '/canais/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/amigos'
    | '/canais/$channelId'
    | '/convite/$code'
    | '/dm/$userId'
    | '/canais'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/amigos'
    | '/_authenticated/canais/$channelId'
    | '/_authenticated/convite/$code'
    | '/_authenticated/dm/$userId'
    | '/_authenticated/canais/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/amigos': {
      id: '/_authenticated/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AuthenticatedAmigosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canais/': {
      id: '/_authenticated/canais/'
      path: '/canais'
      fullPath: '/canais/'
      preLoaderRoute: typeof AuthenticatedCanaisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canais/$channelId': {
      id: '/_authenticated/canais/$channelId'
      path: '/canais/$channelId'
      fullPath: '/canais/$channelId'
      preLoaderRoute: typeof AuthenticatedCanaisChannelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/convite/$code': {
      id: '/_authenticated/convite/$code'
      path: '/convite/$code'
      fullPath: '/convite/$code'
      preLoaderRoute: typeof AuthenticatedConviteCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dm/$userId': {
      id: '/_authenticated/dm/$userId'
      path: '/dm/$userId'
      fullPath: '/dm/$userId'
      preLoaderRoute: typeof AuthenticatedDmUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAmigosRoute: typeof AuthenticatedAmigosRoute
  AuthenticatedCanaisChannelIdRoute: typeof AuthenticatedCanaisChannelIdRoute
  AuthenticatedConviteCodeRoute: typeof AuthenticatedConviteCodeRoute
  AuthenticatedDmUserIdRoute: typeof AuthenticatedDmUserIdRoute
  AuthenticatedCanaisIndexRoute: typeof AuthenticatedCanaisIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAmigosRoute: AuthenticatedAmigosRoute,
  AuthenticatedCanaisChannelIdRoute: AuthenticatedCanaisChannelIdRoute,
  AuthenticatedConviteCodeRoute: AuthenticatedConviteCodeRoute,
  AuthenticatedDmUserIdRoute: AuthenticatedDmUserIdRoute,
  AuthenticatedCanaisIndexRoute: AuthenticatedCanaisIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
